### ISSUE TITLE
please use url's for images

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em-apps#3]
In FDEM_VMD_LayeredEarth
![image](https://cloud.githubusercontent.com/assets/6361812/22384976/90ac66dc-e485-11e6-9491-48924cbc3dd9.png)

**Comment by lheagy** [comment]
also in TDEM_HorizontalLoop_LayeredEarth (I can't upload these images to microsoft)

**Comment by sgkang** [comment]
This is caused by old em_examples repo, which is deployed to pypi. 
Once simpeg is on pypi, we can first test em_examples branch, then 
deploy to pypi.

**Comment by lheagy** [comment]
ah, kk thanks - I will update (simpeg has been deployed)

**Comment by lheagy** [comment]
closed with geoscixyz/em_examples#63
