### ISSUE TITLE
DC Building Pseudosections

### ISSUE THREAD

**Issue by dougoldenburg** [geoscixyz/em-apps#36]
Can this be augmented to include a pole-pole result. 
![image](https://user-images.githubusercontent.com/8864444/42136611-b0bb320a-7d13-11e8-912e-7f8dede1acb7.png)

**Comment by lheagy** [comment]
@micmitch: do you have the originals for this?

**Comment by micmitch** [comment]
Can you give some idea of where this image was from? Looks like it was probably done with google draw... Hopefully the original drawing is in the same place as the saved image.

**Comment by lheagy** [comment]
It is in the [DC_Building_Pseudosections app](https://github.com/geoscixyz/em_apps/blob/master/notebooks/DC_Building_Pseudosections.ipynb). @thast also did some development here

**Comment by micmitch** [comment]
hmm... I'm sure that I would have saved the original somewhere but I have no idea where it ended up. No sign of it in em_apps or my personal drive folder.

**Comment by thast** [comment]
Do not remember creating this one and cannot find it on the drive either. I guess at this point it will take less time to re-create it. I can take a crack at it later today.

**Comment by lheagy** [comment]
Thanks @thast!

**Comment by thast** [comment]
![polepole_pseudosections](https://user-images.githubusercontent.com/13682747/42336373-61769f04-8038-11e8-947b-4fe837784062.png)

**Comment by thast** [comment]
The google drawings are available in the drive GeosciImages/DCR

**Comment by lheagy** [comment]
- [x] still needs to be added to the DC_BuildingPseudosections app

**Comment by thast** [comment]
done.
