### ISSUE TITLE
TDEM grounded bipole at the surface

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em-apps#41]
App for a grounded bipole over a halfspace (TDEM)
- 3D tensor mesh
- user can define conductivity of the half-space
- solve 3D problem
- viewer / app on the fields object (view currents, electric and magnetic fields, db/dt) through time

![image](https://user-images.githubusercontent.com/6361812/42239068-a5f75a9c-7eb7-11e8-9a9b-f2329f8d4c16.png)

**Comment by sgkang** [comment]
Done. Related to #46
