### ISSUE TITLE
No module named 'em_examples'

### ISSUE THREAD

**Issue by leomiquelutti** [geoscixyz/em-apps#53]
Dear,

I followed instructions regarding running em-apps on Azure Notebooks but it didn't work. There's the output. Should I have some "!pip install ..." somewhere?

![image](https://user-images.githubusercontent.com/9113903/44067518-4a41d960-9f4c-11e8-8db3-4719bc0a998a.png)

I could ran previous version of em-apps (cloned from Lindsey personal repo) very sound. What can I be doing wrong?

Thanks in advance,
Leonardo

**Comment by leomiquelutti** [comment]
And following instructions for installing em-apps locally, the same error occurred through 

```
conda env create -f environment.yml
source activate em-apps-environment
```

**Comment by lheagy** [comment]
Hi @leomiquelutti, we have been fiddling a bit with Azure to try and automatically install `em_examples`, but we don't have it totally worked out yet. There are two options, 

1. at the top of the notebook you can add
`!pip install em_examples`  

2. on azure, if you change your kernel to python 3.6, it should work

![image](https://user-images.githubusercontent.com/6361812/44110195-f712744e-9fb3-11e8-856c-d8c9cd571da7.png)


Running it locally... `em_examples` should be installed when you create the environment. Did you launch the notebook from the same terminal while still in the conda environment?  

```
conda env create -f environment.yml
source activate em-apps-environment
jupyter notebook
```

**Comment by leomiquelutti** [comment]
Hi @lheagy,

thank you very much. Selecting Python 3.6 worked fine.

Regarding the environment, I **probably** launched Jupyter Notebook from Anaconda Navigator (Python 2.7) *after* following the environment instructions. 

Right after opening this issue I successfully installed locally through pip (requirements.txt).

**Comment by lheagy** [comment]
Excellent! I am glad you are up and running :tada: 

I will close this issue, feel free to re-open it if you run into other challenges
